# Generated by Django 3.0.6 on 2020-05-17 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='rwfw_item_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_icon', models.ImageField(upload_to='images/')),
                ('item_desc', models.CharField(max_length=200)),
            ],
        ),
    ]
