# Generated by Django 3.0.6 on 2020-05-24 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rwfw_main', '0002_rwfw_item_table_item_head'),
    ]

    operations = [
        migrations.AddField(
            model_name='rwfw_item_table',
            name='item_order',
            field=models.IntegerField(default='1'),
        ),
    ]
