# Generated by Django 3.0.6 on 2020-05-24 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='rwfw_image_downloaded',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dwn_version', models.CharField(default='1.1', max_length=20)),
                ('dwm_build', models.CharField(default='100', max_length=20)),
                ('dwn_index', models.IntegerField(default=0)),
                ('dwn_path', models.CharField(default='Builds/', max_length=50)),
                ('dwm_avail', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='rwfw_image_repo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_ip', models.GenericIPAddressField()),
                ('repo_name', models.CharField(default='default', max_length=20)),
                ('repo_user', models.CharField(default='root', max_length=20)),
                ('repo_pass', models.CharField(default='root', max_length=20)),
                ('repo_base', models.CharField(default='/projects', max_length=50)),
                ('repo_verson', models.CharField(default='1.1', max_length=20)),
                ('repo_build', models.CharField(default='0', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='rwfw_image_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_img', models.ImageField(upload_to='images/')),
                ('type_name', models.CharField(default='ova', max_length=20)),
                ('type_count', models.IntegerField(default=2)),
            ],
        ),
    ]
