# Generated by Django 3.0.6 on 2020-05-24 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rwfw_images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rwfw_image_downloaded',
            name='dwn_type',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='rwfw_image_repo',
            name='repo_type',
            field=models.IntegerField(default=1),
        ),
    ]
