# Generated by Django 3.0.6 on 2020-06-07 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='rwfw_nw_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_img', models.ImageField(upload_to='images/')),
                ('type_name', models.CharField(default='ova', max_length=20)),
            ],
        ),
    ]
