# Generated by Django 3.0.6 on 2020-06-07 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rwfw_networks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='rwfw_nw_system',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nw_name', models.CharField(default='test', max_length=20)),
                ('nw_ip', models.GenericIPAddressField()),
                ('nw_hostname', models.CharField(default='localhost', max_length=100)),
                ('nw_port', models.IntegerField(default=22)),
                ('nw_user', models.CharField(default='test', max_length=20)),
                ('nw_pass', models.CharField(default='test', max_length=20)),
                ('nw_type', models.IntegerField(default=1)),
                ('nw_mgmt_vlan', models.CharField(default=None, max_length=20)),
                ('nw_data1_vlan', models.CharField(default=None, max_length=20)),
                ('nw_data2_vlan', models.CharField(default=None, max_length=20)),
                ('nw_host_id', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='rwfw_nw_vlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vlan_name', models.CharField(default='default', max_length=20)),
                ('vlan_vlan', models.CharField(default='default', max_length=20)),
                ('vlan_host_id', models.IntegerField(default=1)),
            ],
        ),
    ]
