# Generated by Django 3.0.6 on 2020-06-07 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rwfw_networks', '0002_rwfw_nw_system_rwfw_nw_vlan'),
    ]

    operations = [
        migrations.AddField(
            model_name='rwfw_nw_vlan',
            name='vlan_label',
            field=models.CharField(default='default', max_length=40),
        ),
    ]
