# Generated by Django 3.0.6 on 2020-05-22 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='rwfw_host_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_ip', models.GenericIPAddressField()),
                ('host_user', models.CharField(default='root', max_length=20)),
                ('host_pass', models.CharField(default='pass', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='rwfw_host_types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_img', models.ImageField(upload_to='images/')),
                ('type_name', models.CharField(default='VMware', max_length=20)),
            ],
        ),
    ]
