# Generated by Django 3.0.6 on 2020-05-22 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rwfw_hosts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rwfw_host_table',
            name='host_type',
            field=models.IntegerField(default=1),
        ),
    ]
