# Generated by Django 3.0.6 on 2020-05-22 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rwfw_hosts', '0002_rwfw_host_table_host_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='rwfw_host_table',
            name='host_name',
            field=models.CharField(default='lavans', max_length=50),
        ),
    ]
