# Generated by Django 3.0.6 on 2020-05-22 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rwfw_hosts', '0003_rwfw_host_table_host_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='rwfw_host_types',
            new_name='rwfw_host_type',
        ),
    ]
