# Generated by Django 3.0.6 on 2020-05-30 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rwfw_utils', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rwfw_utils_imgdownload',
            name='json_path',
        ),
    ]
