# Generated by Django 3.0.6 on 2020-05-30 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rwfw_utils', '0002_remove_rwfw_utils_imgdownload_json_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='rwfw_utils_imgdownload',
            name='json_config',
            field=models.FileField(default='img.json', max_length=200, upload_to='jsons/'),
        ),
    ]
